### ISSUE TITLE
how to use with chromedriver -> add example

### ISSUE THREAD

**Issue by srghma** [slamdata/purescript-lunapark#12]
I see in code that it was already tried

could someone give me an example?

**Comment by cryogenian** [comment]
```purescript
main = launchAff do
  interpreterOrError ← init "http://localhost:4444/wd/hub" { alwaysMatch: [], firstMatch: [[BrowserName Chrome]] }
  case intepreterOrError of
    Left err → throwError $ error "An error during selenium session initialization occured"
    Right interpret → Run.runBaseAff' $ Run.runExcept $ interpret do
      go "http://my-site.com"
      el ← findElement $ ByCss $ CSS.fromString ".my-class"
      clickEl el
      login ← findElement $ ByCss $ CSS.fromString "#login"
      password ← findElement $ ByCss $ CSS.fromString "#password"
      moveTo { origin: login, x: 0, y: 0, duration: Milliseconds 1000.0 }
      click
      sendKeys "login"
      moveTo { origin: password, x: 0, y: 0, duration: Milliseconds 100.0 }
      sendKeys "secret"
      sendKeys "\\xE007"
```

`init` creates an interpreter using uri pointing to selenium webdriver endpoint with https://github.com/slamdata/purescript-lunapark/blob/master/src/Lunapark/Types.purs#L529 as the second argument. 

`interpret` here is a function that takes `Run (lunapark :: LUNAPARK|F)` which has different functions like `go`, `clickEl` `findElement` (this file https://github.com/slamdata/purescript-lunapark/blob/master/src/Lunapark/LunaparkF.purs) and returns 
`type BaseRun r = R.Run
  ( except ∷ EXCEPT LE.Error
  , aff ∷ R.AFF
  , effect ∷ R.EFFECT
  | r)`

Which is interpreted to `Aff` using `Run.runBaseAff' $ Run.runExcept`.

**Comment by cryogenian** [comment]
Maybe I didn't totally understand your question though? Like starting `chromedriver.exe` as usual and point `init` to its endpoint?

**Comment by srghma** [comment]
thx for example, I thought it will be complicated

this is my solution https://github.com/srghma/purescript-halogen-nextjs/blob/a43b003e8b84aa4554c0e5554738400cbf9cd8d1/packages/feature-tests/FeatureTests/Main.purs#L77-L114

https://github.com/srghma/purescript-halogen-nextjs/blob/a43b003e8b84aa4554c0e5554738400cbf9cd8d1/dev-commands/dev/default.nix#L98-L115
