### ISSUE TITLE
retry find within timeout, retry combinators

### ISSUE THREAD

**Issue by srghma** [slamdata/purescript-lunapark#17]
I could use webdriver implicit timeout feature

but the function similar to `recovering`  from https://pursuit.purescript.org/packages/purescript-aff-retry/1.2.1/docs/Effect.Aff.Retry 
would be better

_____

that's why I wanted to ask

- what have happened with https://github.com/slamdata/purescript-moonshine/blob/master/src/Moonshine/Retry.purs
- and what is the current approach to retry

for now I think I will probably make a Run wrapper around https://pursuit.purescript.org/packages/purescript-aff-retry

**Comment by cryogenian** [comment]
* `purescript-moonshine` was one of approaching to build up specs around lunapark and so on. We found it's not so useful as we wanted, and switched to purescript-mote. 
* Using `Run` wrapper arround `purescript-aff-retry` or hand-written things looking like `CATCH` from moonshine, or using monad transformer around `Aff` should work.

**Comment by srghma** [comment]
tnx for answering

could you explain one more thing

Why `CATCH` was introduced in moonshine?

because `EXCEPT` already has `catch` function (except it peels off `except ∷ RE.EXCEPT e` from the input, but `CATCH` is not)

**Comment by cryogenian** [comment]
The fact `EXCEPT`'s `catch` removes `EXCEPT` from `Run` is a problem actually, because it's impossible to run `retry` with such behaviour. There were other problems (something with except being non-algebraic) but I can't recollect precisely, sorry.

**Comment by srghma** [comment]
implemented without CATCH, using `Except.runExcept`, not `Except.catch`

```
module FeatureTests.FeatureTestSpecUtils.AffRetry where

import Effect.Aff.Retry
import Protolude

import Data.Array (uncons)
import Effect.Aff (delay)
import Prim.Row (class Cons) as Row
import Run (Run, AFF)
import Run as Run
import Run.Except (EXCEPT)
import Run.Except as Run
import Unsafe.Coerce (unsafeCoerce)

-- from https://github.com/Unisay/purescript-aff-retry/blob/936fad803e3610f149df724ead288657a905cb84/src/Effect/Aff/Retry.purs#L201
-- without changes
-- TODO: expose
applyAndDelay :: ∀ m . MonadAff m
  => RetryPolicyM m
  -> RetryStatus
  -> m (Maybe RetryStatus)
applyAndDelay policy retryStatus = do
    res <- applyPolicy policy retryStatus
    case res of
      Just nextRetryStatus@(RetryStatus { previousDelay: pd }) ->
        maybe (pure unit) (delay >>> liftAff) pd
          $> Just nextRetryStatus
      Nothing -> pure Nothing

type Check = RetryStatus -> Error -> Aff Boolean

-- from https://github.com/purescript-webrow/webrow/blob/68144f421b6652b93bb9ceeb9ed69762286ae905/src/WebRow/PostgreSQL/PG.purs#L135
--
-- | Run.expand definition is based on `Union` constraint
-- | We want to use Row.Cons here instead
expand' ∷ ∀ l b t t_. Row.Cons l b t_ t ⇒ SProxy l → Run t_ ~> Run t
expand' _ = unsafeCoerce

runExcept' ∷ ∀ e a r. Run (except ∷ EXCEPT e | r) a → Run (except ∷ EXCEPT e | r) (Either e a)
runExcept' = expand' (SProxy :: SProxy "except") <<< Run.runExcept

recovering
  :: ∀ r a e
   . RetryPolicyM Aff
  -> Array Check
  -> (RetryStatus -> Run ( aff :: AFF, except ∷ EXCEPT Error | r ) a)
  -> Run ( aff :: AFF, except ∷ EXCEPT Error | r ) a
recovering policy checks f = go defaultRetryStatus
  where
    go :: RetryStatus -> Run ( aff :: AFF, except ∷ EXCEPT Error | r ) a
    go status = runExcept' (f status) >>= either (recover checks) pure
      where
        recover
          :: Array Check
          -> Error
          -> Run ( aff :: AFF, except ∷ EXCEPT Error | r ) a
        recover chks e =
          case uncons chks of
              Nothing -> Run.throw e
              Just headTail -> handle e headTail

        handle
          :: Error
          -> { head :: Check, tail :: Array Check }
          -> Run ( aff :: AFF, except ∷ EXCEPT Error | r ) a
        handle e hs =
          Run.liftAff (hs.head status e) >>=
            if _
              then Run.liftAff (applyAndDelay policy status) >>= maybe (Run.throw e) go
              else recover hs.tail e
```

**Comment by cryogenian** [comment]
Ok :+1: 

I'm closing this issue because 
+ There is a solution you found
+ Retrying isn't actually matter of lunapark

**Comment by srghma** [comment]
seems like I have encountered your problem `something with except being non-algebraic` too

because my solution doesnt work

```
  RunAffRetry.recovering
    (AffRetry.constantDelay (Milliseconds 200.0) <> AffRetry.limitRetries 10)
    [\_ _ -> pure true]
    (\_ -> Lunapark.findElement
      (Lunapark.ByCss $ CSS.Selector (CSS.Refinement [CSS.Id "usernameOrEmail-helper"]) CSS.Star)
    )
    >>= Lunapark.getText
    >>= \text -> text `shouldEqual` "Username or email is not found"
```

throws error in runtime

```
  [runFeatureTest] Lunapark error: Response with error message:
  error type: no such element
  message: no such element: Unable to locate element: {"method":"css selector","selector":"#usernameOrEmail-helper"}
  (Session info: chrome=85.0.4183.121)
  stacktrace: #0 0x564f7c021a39 <unknown>
```

the underlying issue is that 

```
  result <- Run.runExcept $ Lunapark.findElement (Lunapark.ByCss $ CSS.Selector (CSS.Refinement [CSS.Id "usernameOrEmail-helper"]) CSS.Star)
  traceM { result }
```

throws error in runtime too, the `{ result }` is never printed

this is really weird for me

because as far as I know Lunapark doesnt throw errors in Effect

I mean it's not like

```
-- expected:
-- resultInside is shown AND result is shown
-- actual:
-- error "asdf" is thrown in runtime
main = do
  (result :: Unit) <- Run.runBaseEffect do
    (resultInside :: Either Error Void) <- Run.runExcept (Run.liftEffect $ throwError $ error "asdf")
    traceM { resultInside }
  traceM { result }
```

it's more like 

```
-- actual:
-- | "log"
-- | { resultInside: Left { value0: 'my error' } }
-- | { result: {} }
main = do
  (result :: Unit) <- Run.runBaseEffect do
    (resultInside :: Either String Void) <- Run.runExcept $ do
       Run.liftEffect $ log "log"
       Run.rethrow $ Left "my error"
    traceM { resultInside }
  traceM { result }
```

**Comment by cryogenian** [comment]
Right, `except` didn't catch our errors too. `CATCH` did iirc.

**Comment by garyb** [comment]
We catch errors using `ExceptT` around lunapark's `Run` in our test DSL, since I couldn't get `CATCH` to work properly. I don't know about using `EXCEPT`, I assume we attempted to invent `CATCH` to fix some reason that `EXCEPT` didn't behave the way we wanted.

**Comment by srghma** [comment]
so `CATCH` doesn't work as expected too sometimes, interesting

------------

there are two different problems AFAIU:

1. how user should catch *EXCEPT errors* thrown from pure user code (already possible with `catch` from `EXCEPT`)

2. how user should catch *js errors* thrown from


```
otherlibcode :: Run ... Unit
otherlibcode = do
  Run.liftEffect $ throw $ error "js error"
```

we need function

```
try :: Run ... a -> Run ... (Either xxx a)
try = Run.liftEffect try
```

https://github.com/natefaubion/purescript-run/issues/32

3. how from user code to catch *EXCEPT errors* that are thrown from other interpreters

(i.e. AFTER interpreter xxx rewrites `Free` strucure)

https://github.com/natefaubion/purescript-run/issues/31

________________

@garyb could you send an example of how `ExceptT` is used?
